### PR TITLE
fix #1003: display breached email in alert

### LINKED ISSUE #1003: When the user has selected to have all breach alerts sent to a single email inbox, the email address shown in an alert email is wrong
image

STR:

1. Sign up/in with a Firefox Account
2. Add and verify a secondary email address (e.g.,  test2@mailinator.com)
3. On `/user/preferences`, select "Send all breach alerts to <primary-email@mailinator.com>
4. Trigger a breach alert to test2@mailinator.com (steps below)
5. Open the breach alert email in the Inbox for primary-email@mailinator.com

Expected results:
The alert email should say "Email address: test2@mailinator.com"

Actual results:
The alert email says "Email address: primary-email@mailinator.com"

Steps to trigger a breach alert for test2@mailinator.com:
```sh
curl http://localhost:6060/hibp/notify -H "Content-Type: application/json" -H "Authorization: Bearer unsafe-default-token-for-dev" -d "{\"breachName\": \"Adobe\", \"hashPrefix\": \"60e411\", \"hashSuffixes\": [\"8eb1c32080fa3ae1a6e3f258d3a25d8ed9\"]}"
```

### PR DESCRIPTION
**Pull request by groovecoder**

### CODE REVIEW

File: template-helpers/emails.js [hunk 1]
```diff
@@ -97,7 +97,7 @@ function getWhatToDos(args) {
 
   // grab different strings for breach alert emails
   if (args.data.root.breachAlert) {
-    headlineId = "what-to-do-after";
+    headlineId = "what-to-do-after-breach";
```
Comment (groovecoder) [inline template-helpers/emails.js]: Also found and fixed this bug while I was in here.
