### PR TITLE
fix #705: check for 'FxiOS' user agent too

### LINKED ISSUE #705: Download Firefox banners appearing in iOS versions of Firefox.
Download Firefox banners incorrectly show up when visiting Firefox Monitor with Firefox for iOS and Firefox Focus for iOS

img_2181

### PR DESCRIPTION
**Pull request by groovecoder**

### CODE REVIEW

File: public/js/analytics_tracking_protection.js [hunk 1]
```diff
@@ -7,7 +7,7 @@
 
 function browserName() {
   try {
-    if (/firefox/i.test(navigator.userAgent)) {
+    if (/firefox|FxiOS/i.test(navigator.userAgent)) {
```
Comment (lesleyjanenorton) [inline public/js/analytics_tracking_protection.js]: Nice! Not showing locally in Focus or Firefox iOS!! LGTM!
