### PR TITLE
fix #1295 add hsts to heroku

### LINKED ISSUE #1295: fx-breach-alerts.herokuapp.com has failed the web security baseline
Site https://fx-breach-alerts.herokuapp.com has failed the web security baseline scan.

The failing tests are:

 Strict-Transport-Security Header Not Set [10035] x 15 
 * https://fx-breach-alerts.herokuapp.com/ (200 OK)
 * https://fx-breach-alerts.herokuapp.com/robots.txt (404 Not Found)
 * https://fx-breach-alerts.herokuapp.com/sitemap.xml (404 Not Found)
 * https://fx-breach-alerts.herokuapp.com/breaches (200 OK)
 * https://fx-breach-alerts.herokuapp.com/security-tips (200 OK)

 Absence of Anti-CSRF Tokens [10202] x 1 
 * https://fx-breach-alerts.herokuapp.com/breaches (200 OK)

This issue was automatically raised.

This issue is managed automatically by the baseline scan:

 * If the failing tests change then it will be updated
 * If it is closed before the tests pass then a new one will be opened
 * When all of the tests pass then it will be closed

Full details, including how to test for these issues locally, can be found on this [Security Baseline Service](https://sql.telemetry.mozilla.org/dashboard/security-baseline-service-latest?p_w53332_site_60280=fx-breach-alerts.herokuapp.com) dashboard.
If you have any questions or concerns please get in contact with @psiinon

### PR DESCRIPTION
**Pull request by groovecoder**

### CODE REVIEW

File: server.js [hunk 1]
```diff
@@ -66,10 +66,9 @@ try {
 })();
 
 // Use helmet to set security headers
-// disable default HSTS; Ops handles it in stage & prod configs
-app.use(helmet({
-  hsts: false,
-}));
+// only enable HSTS on heroku; Ops handles it in stage & prod configs
+const hsts = AppConstants.NODE_ENV === "heroku" ? true : false;
```
Comment (pdehaan) [inline server.js]: `AppConstants.NODE_ENV === "heroku"` is already a Boolean, so no need to re-cast to `? true : false`, but yeah. 👍
