### PR TITLE
fix #799: Add markup to { $breachCount } after grabbing localized strings.

### LINKED ISSUE #799: Wrong pluralization when scanned email only has 1 breach?
Found in https://fx-breach-alerts.herokuapp.com/__version__

```js
{
  commit: "f5c4b5e88e1df37b19125eff19b2fea0bf497ea8",
  version: "f5c4b5e88e1df37b19125eff19b2fea0bf497ea8",
  source: "https://github.com/mozilla/blurts-server"
}
```

### Steps to reproduce:

1. https://fx-breach-alerts.herokuapp.com/scan
1. Search for "peeter@peter.com"

firefox_monitor___scan_results

I'm not signed in or anything and I randomly typoed an email address. I thought this string would have been `guest-scan-results-headline` in the FTL, so not sure why it is showing the plural "breaches" for `[one]`, vs `*[other]`...

https://github.com/mozilla/blurts-server/blob/f5c4b5e88e1df37b19125eff19b2fea0bf497ea8/locales/en/app.ftl#L307-L311

For comparison sake, here's the same page when I search for "peter@peter.com":

firefox_monitor___scan_results

### PR DESCRIPTION
**Pull request by lesleyjanenorton**
This grabs the localized copy before wrapping `{$ breachCount }` in `<span class="medium"></span>`.
Fluent doesn't interpret `{ $breachCount }` when it's wrapped in markup and the default `*[other]` string is currently being returned no matter the actual `{ $breachCount }`.
screen shot 2019-02-21 at 10 17 11 am

### CODE REVIEW

**Comment by groovecoder** [comment]
This should fix #799 right?

**Comment by lesleyjanenorton** [comment]
@groovecoder yep! I didn't realize there was an issue already filed for this but yes, should fix.

File: hbs-helpers.js [hunk 1]
```diff
@@ -42,12 +42,14 @@ function localizedBreachDataClasses(supportedLocales, dataClasses, args) {
...
-    if (["breachName", "breachCount"].includes(key)) {
-      args.hash[key] = `<span class="medium">${args.hash[key]}</span>`;
-    }
+  if (args.hash.breachName) {
+    args.hash.breachName = `<span class="medium">${args.hash.breachName}</span>`;
   }
-  return LocaleUtils.fluentFormat(supportedLocales, id, args.hash);
+  let localizedStrings = LocaleUtils.fluentFormat(supportedLocales, id, args.hash);
+  if (args.hash.breachCount) {
+    localizedStrings = localizedStrings.replace(/\d+/, `<span class="medium">${args.hash.breachCount}</span>`);
```
Comment (pdehaan) [inline hbs-helpers.js]: My gut is telling me this may not work for small edge cases like "zero" (ref https://github.com/mozilla/blurts-server/issues/786#issuecomment-465789528).

But maybe that isn't relevant if the "zero" isn't in the arg hash. I guess this would only potentially impact these (which were the only instances of "zero" that I found in the app.ftl files):

https://github.com/mozilla/blurts-server/blob/c24b817c8510dac8fe6b4a1445459a9ce98f9bdd/locales/en/app.ftl#L298-L299

Comment (pdehaan) [reply hbs-helpers.js]: Actually, another thing that occurred to me was if we're assuming any digit is a `$breachCount`, do we need to worry about any potential email addresses or breach names with numbers in them?

I found these 2 instances of `$breachCount` w/ `$featuredBreach`:

https://github.com/mozilla/blurts-server/blob/1388d1406613059921718503f71ee2b8c43bca48/locales/en/app.ftl#L149-L161

And this 1 instance of `$breachCount` w/ `$userEmail`:

https://github.com/mozilla/blurts-server/blob/1388d1406613059921718503f71ee2b8c43bca48/locales/en/app.ftl#L301-L305

And a few breach names that happen to have numbers in the name/title:

- [Collection #1](https://fx-breach-alerts.herokuapp.com/?breach=collection1)
- [Hub4Tech](https://fx-breach-alerts.herokuapp.com/?breach=hub4tech)
- [17173](https://fx-breach-alerts.herokuapp.com/?breach=17173)
- [2fast4u](https://fx-breach-alerts.herokuapp.com/?breach=2FAST4U)
- [000webhost](https://fx-breach-alerts.herokuapp.com/?breach=000WEBHOST)
- [7k7k](https://fx-breach-alerts.herokuapp.com/?breach=7K7K)
- [B2B USA BUSINESSES](https://fx-breach-alerts.herokuapp.com/?breach=B2BUSABUSINESSES)
- [Bell 2017 breach](https://fx-breach-alerts.herokuapp.com/?breach=BELL2017)
- [R2 2017 breach](https://fx-breach-alerts.herokuapp.com/?breach=r2-2017)
