### PR TITLE
getting breaches by name + updates

### LINKED ISSUE #150: Remove the 'AllMusic' test fixture breach?
Randomly spotted, but something feels weird to me...

- https://fx-breach-alerts.herokuapp.com/?breach=AllMusic has some details, and a logo.
- https://mozilla.invisionapp.com/share/KEIV66OTS23#/screens/297625875 lists a description (but is just a Photoshop mockup, so not 100% reliable as a data source -- but seems odd that the description looks so legit)
- https://haveibeenpwned.com/PwnedWebsites doesn't seem to any mention of "AllMusic" or "All Music", so I can't even find the breach on HIBP site to see what description they have (if any).

firefox_monitor_-_allmusic

### LINKED ISSUE #213: "Please enter a valid email" message is not displayed if trying to submit an invalid email by pressing the "Enter" key
Via @Softvision-MariusComan in https://github.com/mozilla/blurts-addon/issues/54:

---

**[Affected versions]:**
- Firefox Release 60.0.2
- Firefox Beta 61.0b14

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the "Firefox Monitor" add-on (0.01 custom built on 20.06.2018) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to the "https://fx-breach-alerts.herokuapp.com/" page.
3. Enter an invalid email in the input field.
4. Press the "Enter" key and observe the behavior.

**[Expected result]:**
- The "Please enter a valid email" message is displayed.

**[Actual result]:**
- Nothing happens.

**[Notes]:**
- This issue is not reproducible if clicking the search button from the right side of the email field.
- Attached a screen recording of the issue: 
rec of the issue

### LINKED ISSUE #215: The "Sign up for alerts" pop-up from the "Firefox Monitor" website cannot be dismissed by any other methods except the "Close" button
Via @Softvision-MariusComan in https://github.com/mozilla/blurts-addon/issues/53

---

**[Affected versions]:**
- Firefox 60.0.2

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the "Firefox Monitor" add-on (0.01 custom built on 20.06.2018) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to the "https://fx-breach-alerts.herokuapp.com/" page.
3. Click the "Sign up for alerts" button.
4. Press the "Esc/Enter" key or click outside the pop-up area.
5. Observe the behavior.

**[Expected result]:**
- The pop-up is dismissed.

**[Actual result]:**
- Nothing happens.

**[Notes]:**
- Attached a screen recording of the issue: 
rec of the issue

### PR DESCRIPTION
**Pull request by lesleyjanenorton**
Getting breaches by name again instead of domain + fixes from previous PR review.

Fixes #150 , fixes #213 , fixes #215 and #39 in the add-on repo.

### CODE REVIEW

File: public/js/monitor.js [hunk 1]
```diff
@@ -127,7 +147,7 @@ async function sha1(message) {
 async function hashEmailAndSend(emailFormSubmitEvent) {
   emailFormSubmitEvent.preventDefault();
   const emailForm = emailFormSubmitEvent.target;
-  if(emailForm.querySelector("input[name=email]").value === ""){
+  if (emailForm.querySelector("input[name=email]").value === "") {
```
Comment (nhnt11) [inline public/js/monitor.js]: nit: we can just do `if (!emailForm.querySelector("input[name=email]).value) {`

File: public/js/monitor.js [hunk 2]
```diff
@@ -57,61 +57,81 @@ function isValidEmail(val) {
...
 }
 
-function showFalseDoor(){
+function showFalseDoor() {
   handleEvents("SignUp");
   removeClass("#false-door", "hidden");
-  document.getElementById("close-false-door").onclick = function (){
+  document.body.style.overflow = "hidden";
+  const falseDoor = document.getElementById("false-door");
+  window.addEventListener("keydown", function listener(e) {
```
Comment (nhnt11) [inline public/js/monitor.js]: the listener function here and the one below added to the false door are different, so removing this one from the false door has no effect. How's this:

https://pastebin.mozilla.org/9088475

File: scripts/load-breaches.js [hunk 3]
```diff
@@ -41,12 +41,14 @@ async function handleBreachesResponse(response) {
 }
 
 (async () => {
-  if (args["--createAMBreach"]) {
-    await DBUtils.createBreach("AllMusic", {
-      Name: "AllMusic",
-      BreachDate: "2015-012-06",
+  if (args["--createExampleBreach"]) {
```
Comment (nhnt11) [inline scripts/load-breaches.js]: can you remove this entire block? I think we can drop support for this example breach stuff at this point.

Comment (lesleyjanenorton) [reply scripts/load-breaches.js]: yep! Do you want to take out --help too? And if not, what should we have the console.log on --help say?

**Comment by lesleyjanenorton** [comment]
updated!

File: README.md [hunk 4]
```diff
@@ -66,7 +66,7 @@ To populate the database with test data, use these scripts in `scripts/`:
 * `node scripts/add-breached-emails.js` adds some breached email records for
   `test[1-3]@test.com` users
 
-Both scripts have `--help` arguments for usage help.
+* `node scripts/add-breached-email.sjs --help` for usage help.
```
Comment (pdehaan) [inline README.md]: nit: this should be "scripts/add-breached-emails.js" (plural emails and a vanilla ".js" extension &mdash; basically just move the period over).

File: public/css/app.css [hunk 5]
```diff
@@ -666,17 +670,19 @@ form span {
   color: #000;
   display: inline-block;
   width: 40vw;
-  min-width: 300px;
+  min-width: 350px;
   max-width: 600px;
   padding: calc(3.33vw + 0.625rem) !important;
   text-align: left;
   box-sizing: border-box;
+  box-shadow: 0 0 9px #0000002e;
```
Comment (pdehaan) [inline public/css/app.css]: Personal question (for another issue/PR), but why sometimes `rgba()` and sometimes `#rrggbbaa` format?
https://caniuse.com/#search=rgba seems to say that `rgba()` support is in the at around 97% whereas `#rrggbbaa` support is unofficial and at around 73%.

File: public/js/monitor.js [hunk 6]
```diff
@@ -57,61 +57,82 @@ function isValidEmail(val) {
...
+    if (e.code !== "Enter" && e.code !== "Escape") {
+      return;
+    }
+    hideFalseDoor();
+    window.removeEventListener("keydown", listener);
+  });
+  falseDoor.addEventListener("click", function listener (e) {
```
Comment (pdehaan) [inline public/js/monitor.js]: I'll be honest and tell you that I don't exactly know how this works (but trust that you and @nhnt11 know what's going on).
But my crude understanding is that you have a function named `listener()` here (and on L118) which does some stuff. I'm not sure how the variable hoisting works in this scenario since my guess is that you're overwriting the hoisted `listener()` function declared earlier. I'd have to try adding a bunch of `console.log()` statements throughout to try and verify the exact hoisting rules in this exact case.
Or, just rename the listener functions to be more unique ("windowKeydownListener" and "falseDoorClickListener") and cross our fingers.

File: public/js/monitor.js [hunk 7]
```diff
@@ -141,25 +162,31 @@ async function hashEmailAndSend(emailFormSubmitEvent) {
...
     handleEvents("Pageview");
   }
 });
-if(document.getElementById("sign-up")){
+
+if (document.getElementById("sign-up")) {
   document.getElementById("sign-up").addEventListener("click", showFalseDoor);
 }
 
+if (document.getElementById("false-door").getAttribute("data-name") === "checkboxChecked") {
```
Comment (pdehaan) [inline public/js/monitor.js]: Does every page/template have a `#false-door` element?
If that ever returns `null` or `undefined`, I suspect this would 💥 on the subsequent `.getAttribute("data-name")` bit.

File: views/partials/scan_form.hbs [hunk 8]
```diff
@@ -3,12 +3,12 @@
       Please enter a valid email.
     </span>
   <div class="input-group">
-    <input class="input-group-field email-to-hash" type="email" name="email" placeholder="Enter Email Address" aria-label="Enter Email Address" />
+    <input class="input-group-field email-to-hash" type="email" name="email" placeholder="Enter Email Address" aria-label="Enter Email Address" tabindex="0" maxlength="80"/>
```
Comment (pdehaan) [inline views/partials/scan_form.hbs]: Why an email address length limit of 80 specifically? Is that a DB limitation, or was allowing longer strings causing some other problem?

File: public/js/monitor.js (hunk 6 above)
Comment (nhnt11) [reply public/js/monitor.js]: yes, good point, let's name these two listeners differently.

File: public/js/monitor.js (hunk 7 above)
Comment (nhnt11) [reply public/js/monitor.js]: I believe every page does have a false door element at this point, but this is a great catch since this may change in the future.

File: views/partials/scan_form.hbs (hunk 8 above)
Comment (nhnt11) [reply views/partials/scan_form.hbs]: It's not a DB limitation. Why are we doing this indeed? :)

**Comment by lesleyjanenorton** [comment]
updated!

File: public/css/app.css (hunk 5 above)
Comment (lesleyjanenorton) [reply public/css/app.css]: I am trying to think of a good answer to this question and I will let you know when I arrive at one.
