### PR TITLE
fix #1084 fix #1146 - only put ids and emails into user object

### LINKED ISSUE #1084: Unable to login to Firefox Monitor using Firefox or Brave. Issue not present using Edge.
Hello,
I was instructed to report this bug here by @groovecoder on Twitter:
https://twitter.com/groovecoder/status/1137412678186614786

**The issue:**
If I visit https://monitor.firefox.com/ using the Firefox browser or the Brave browser, and try to log in using my Firefox account, after having provided my email address, password, MFA code, and having clicked "Verify", I'm met with the following error message:

Attachment

**The temporary workaround:**
Funnily enough if I try to log in to Firefox Monitor with the same Firefox account using Microsoft Edge, no bug is present and I'm able to log in successfully.

**More info:**
Listed here are version numbers of the browsers and OSes used as well as a few other information that might be relevant.

*Firefox browser (Version 67.0.1)*
Tested the bug both in regular and Private mode by disabling all add-ons and by setting Content Blocking to Standard.

*Brave browser (Version 0.65.118 Chromium: 75.0.3770.80)*
Tested the bug by disabling all extensions, and by disabling some built-in privacy and security settings.

*Edge browser (Version 44.17763.1.0)*
Test done with all extensions disabled.

*Device (laptop)*
Windows 10 (Version 1809 OS Build 17763.529)

Before being confronted with this bug (a few days ago) I was able to successfully add all my email addresses to Firefox Monitor.

I hope you'll be able to reproduce, identify, and fix this soon.
Kind Regards.

### LINKED ISSUE #1146: Cant sign in to monitor.firefox.com. Error - "You must be signed in to your Firefox Account."
On trying to sign in to https://monitor.firefox.com/user/dashboard, it simply keeps giving error "You must be signed in to your Firefox Account."

been facing this since 07/22, even though i was able to add multiple emails to monitoring service initially. but been unable to login to the monitor service on chrome or firefox.

### PR DESCRIPTION
**Pull request by groovecoder**
When a user adds many email addresses, joining all of their full
email_addresses records data into the session user object makes the
client-sessions object larger than the cookie size limit of Firefox.

This temporary fix joins only the ids and emails of the records, because
they are the only columns we're using. This cuts the object size down by
approx. 70%.

https://github.com/mozilla/blurts-server/issues/1148 tracks moving
session data to the back-end.

### CODE REVIEW

**Comment by groovecoder** [comment]
@lesleyjanenorton - can you (code- and spot-)check if we are using anything other than the `id` and `email` fields of the `email_addresses` object on the session user? This change passes all tests and spot-checks, but I'd like to be sure we're not breaking something I've forgotten about.

**Comment by groovecoder** [comment]
fixes #1067

File: scan-results.js [hunk 1]
```diff
@@ -35,8 +35,13 @@ const scanResult = async(req, selfScan=false) => {
...
 
-    if (!selfScan && signedInUser && sha1(signedInUser.email) === req.body.emailHash) {
-      selfScan = true;
+    if (signedInUser) {
+      for (const emailAddress of signedInUser.email_addresses) {
+        if (!selfScan && sha1(emailAddress.email) === req.body.emailHash) {
+          selfScan = true;
+          break;
+        }
+      }
```
Comment (pdehaan) [inline scan-results.js]: Could possibly use [`Array.some()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some), but this looks good.

```js
// maybe?
if (signedInUser) {
  selfScan = signedInUser.email_addresses.some(emailAddress => sha1(emailAddress.email) === req.body.emailHash);
}
```

**Comment by lesleyjanenorton** [comment]
@groovecoder I mentioned `getNewBreachesForEmailEntriesSinceDate(verifiedEmails, user.breaches_last_shown);` in the meeting but it looks like this doesn't negatively affect it at all. Unless I am also missing something, I think we're good to go here!

**Comment by groovecoder** [comment]
Thanks!
